travis:
  secure:
    BINSTAR_TOKEN: f1vVwrJ+ZthaCLfFOOKt2P4T2FxDdXyRtvmkEVarZAg6u/tiwAm+O69wfTLa5V23BTfh0Ec5XgbtPEdEbBkA0ARg+bsq56dZE7J54DahXYxrCTa8FX/unzWbJRAnbwbqiLvtyIFaJj1i39go1JLDXfrq+y5SaiSto44B7icIvM3Tk74ZwczM4vAjOQ+2gfmFSG8TqD2UbtHn3prM9wuJ31Qf5zAOT15JdQc+jaQNwuxhzirF7ucOjULvB8XCAgfcyW6eTf9M6MvyQ/EcWO4dxbCquovDRCLUztASbQPzRPcmyhuLw1e98elic75OLx//gNlLUTpugdCkWHzB0bYyYvefXUtlOL/N24+5k3uP9qQBNpTmtLkQeKNCBxcs+E/VVYPB5Y2SAOvP6Y/n1FDQRZ4/J9zBDw5tkJHchtqXJHz5uZQq9CkwBP6SgJHFt3IAAeAc0daPbSCRYM0U2r7BGNnywlJypX87uAz3PbF1QTq80JFxTcqY4SOgCKb7Twnejs/+0DyEwPlERfqdpPp2qIvWHkjPLTSbhVwn6Hr+c6Klp2HFMDkSOIjVJ1mn3gw8P4vMMgC6aH1GLeaZF4l+hegHaYMq8emtjW6SGmwxq9VPAph6EwJ20QDE5bdJ4IUfGFNu07rdLZ0j/XrPb/4AlnLevxmYd1oba7nOeQkiVuM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
